name: hr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.6.3
  dio: ^5.8.0+1
  firebase_core: ^3.11.0
  firebase_database: ^11.3.3
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.3.0
  intl: ^0.20.2
  json: ^0.20.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
